# Generated by Django 4.2 on 2023-04-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "user_name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("password", models.TextField()),
            ],
            options={
                "db_table": "employee",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=30)),
                ("category", models.CharField(max_length=30)),
                ("date_of_stock", models.DateTimeField()),
            ],
            options={
                "db_table": "item",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "warehouse",
                "managed": False,
            },
        ),
    ]
